"""Offline importer: read solver range screenshots and write tools/screenshot_ranges.py.

Requires Pillow (dev-only; NOT imported by the analysis pipeline). The screenshots
live in "screenshots/", sorted by filename = capture order. That order is,
by construction (see project notes):
  0-4  : RFI for UTG, HJ, CO, BTN, SB
  5-9  : facing an open, opener=UTG, hero = HJ, CO, BTN, SB, BB
  10-13: opener=HJ, hero = CO, BTN, SB, BB
  14-16: opener=CO, hero = BTN, SB, BB
  17-18: opener=BTN, hero = SB, BB
  19   : opener=SB, hero = BB
Colours: red=raise/3bet, dark red=all-in, green=call, blue=fold.

Run:  python3 tools/screenshot_import.py   (regenerates tools/screenshot_ranges.py)
"""
import glob, os
from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SHOTS = sorted(glob.glob(os.path.join(ROOT, "screenshots", "*.png")))
RANKS = "AKQJT98765432"

# file index -> spot.  ("RFI", pos) or ("VS", hero, opener)
SPOTS = [
    ("RFI", "UTG"), ("RFI", "HJ"), ("RFI", "CO"), ("RFI", "BTN"), ("RFI", "SB"),
    ("VS", "HJ", "UTG"), ("VS", "CO", "UTG"), ("VS", "BTN", "UTG"), ("VS", "SB", "UTG"), ("VS", "BB", "UTG"),
    ("VS", "CO", "HJ"), ("VS", "BTN", "HJ"), ("VS", "SB", "HJ"), ("VS", "BB", "HJ"),
    ("VS", "BTN", "CO"), ("VS", "SB", "CO"), ("VS", "BB", "CO"),
    ("VS", "SB", "BTN"), ("VS", "BB", "BTN"),
    ("VS", "BB", "SB"),
]

def label(i, j):
    hi, lo = RANKS[i], RANKS[j]
    return hi + lo if i == j else (hi + lo + "s" if i < j else lo + hi + "o")

def classify(r, g, b):
    if r > g + 45 and r > b + 40:            # reddish
        return "a" if r < 190 else "r"       # dark red = all-in
    if g > r and g >= b - 8 and g > 115:     # green
        return "c"
    if b > 115 and b > g - 10 and b > r:     # blue
        return "f"
    return None

def parse(path):
    im = Image.open(path).convert("RGB"); px = im.load(); W, H = im.size
    isc = lambda p: classify(*p) is not None
    x = int(W * 0.05); top = bot = None
    for y in range(int(H * 0.10), H):
        if isc(px[x, y]): top = y; break
    for y in range(H - 1, int(H * 0.5), -1):
        if isc(px[x, y]): bot = y; break
    ymid = (top + bot) // 2; left = right = None
    for xx in range(0, W):
        if isc(px[xx, ymid]): left = xx; break
    for xx in range(W - 1, 0, -1):
        if isc(px[xx, ymid]): right = xx; break
    cw = (right - left) / 13.0; ch = (bot - top) / 13.0
    out = {}
    for i in range(13):
        for j in range(13):
            x0 = int(left + j * cw); x1 = int(left + (j + 1) * cw)
            y0 = int(top + i * ch); y1 = int(top + (i + 1) * ch)
            mx = int(cw * 0.1); my = int(ch * 0.12)
            cnt = {"r": 0, "c": 0, "f": 0, "a": 0}; tot = 0
            for yy in range(y0 + my, y1 - my, 2):
                for xx in range(x0 + mx, x1 - mx, 2):
                    k = classify(*px[xx, yy])
                    if k: cnt[k] += 1; tot += 1
            if tot == 0:
                continue
            out[label(i, j)] = {k: 100.0 * cnt[k] / tot for k in cnt}
    return out

def clean(d):
    """Drop <4% noise, renormalise to integers summing to 100."""
    d = {k: v for k, v in d.items() if v >= 4}
    s = sum(d.values())
    if s <= 0:
        return {}
    d = {k: round(100 * v / s) for k, v in d.items()}
    # fix rounding to sum 100
    diff = 100 - sum(d.values())
    if diff and d:
        mk = max(d, key=d.get); d[mk] += diff
    return d

RFI = {}
VSOPEN = {}
for path, spot in zip(SHOTS, SPOTS):
    grid = parse(path)
    if spot[0] == "RFI":
        pos = spot[1]; out = {}
        for h, v in grid.items():
            c = clean(v)
            if c.get("f", 0) >= 100:   # pure fold -> omit (absent = fold)
                continue
            # full split: r=raise, c=limp/complete (SB), f=fold, a=open-jam
            out[h] = {"r": c.get("r", 0), "c": c.get("c", 0), "f": c.get("f", 0), "a": c.get("a", 0)}
        RFI[pos] = out
    else:
        _, hero, opener = spot
        out = {}
        for h, v in grid.items():
            c = clean(v)
            if c.get("f", 0) >= 100:   # pure fold -> omit (absent = fold)
                continue
            out[h] = {"r": c.get("r", 0), "c": c.get("c", 0), "f": c.get("f", 0), "a": c.get("a", 0)}
        VSOPEN.setdefault(hero, {})[opener] = out

with open(os.path.join(HERE, "screenshot_ranges.py"), "w", encoding="utf-8") as fp:
    fp.write('"""AUTO-GENERATED by tools/screenshot_import.py from solver range screenshots.\n')
    fp.write('Do not edit by hand; re-run the importer to refresh.\n')
    fp.write('SHOT_RFI[pos] = {hand: {r,c,f,a}}.  SHOT_VSOPEN[hero][opener] = {hand: {r,c,f,a}}.\n"""\n\n')
    fp.write("SHOT_RFI = {\n")
    for pos in ("UTG", "HJ", "CO", "BTN", "SB"):
        fp.write("    %r: %r,\n" % (pos, RFI.get(pos, {})))
    fp.write("}\n\n")
    fp.write("SHOT_VSOPEN = {\n")
    for hero in VSOPEN:
        fp.write("    %r: {\n" % hero)
        for opener in VSOPEN[hero]:
            fp.write("        %r: %r,\n" % (opener, VSOPEN[hero][opener]))
        fp.write("    },\n")
    fp.write("}\n")
print("wrote tools/screenshot_ranges.py")
